name: Sync Ninja README.md

on:
  push:
    # Trigger if an the Ninja README is changed on main
    branches:
      - "main"
    paths:
      - "inlang/source-code/github-lint-action/README.md"

jobs:
  sync-ninja-readme:
    name: Sync Ninja README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Pushes README.md to action repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.INLANG_BOT_TOKEN }}
        with:
          source_file: 'inlang/source-code/github-lint-action/README.md'
          destination_repo: 'opral/ninja-i18n-action'
          user_email: 'hello@inlang.com'
          user_name: 'inlang-bot'
          commit_message: '[v${{ env.LINT_ACTION_PACKAGE_VERSION }}]: update README.md'
