name: Ninja i18n action

on: pull_request_target

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions: 
  pull-requests: write

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        id: checkout
        uses: actions/checkout@v4
        with:
          path: target

      - name: Wait for the merge commit SHA
        run: |
          MERGE_COMMIT_SHA=""
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}

          echo "Waiting for merge commit SHA for PR #${PR_NUMBER}..."

          # Polling GitHub API to get the merge commit SHA
          while [ -z "$MERGE_COMMIT_SHA" ] || [ "$MERGE_COMMIT_SHA" == "null" ]; do
            RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER")
            MERGE_COMMIT_SHA=$(echo $RESPONSE | jq -r '.merge_commit_sha')

            if [ "$MERGE_COMMIT_SHA" != "null" ]; then
              echo "Merge commit SHA found: $MERGE_COMMIT_SHA"
              break
            else
              echo "Merge commit SHA not available yet. Waiting 30 seconds..."
              sleep 30
            fi
          done

      - name: Checkout merge
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          path: merge

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies in target
        run: pnpm install
        working-directory: target

      - name: Build in target
        run: pnpm --filter @inlang/github-lint-action... build
        working-directory: target

      - name: Test Local Action
        id: test-action
        uses: ./target/inlang/source-code/github-lint-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
