on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  changeset:
    # if: github.event.pull_request.merged == true && github.event.pull_request.head.label == 'changeset-release/main'
    runs-on: ubuntu-latest

    steps:
      - name: log
        run: |
          echo ${{ github.event.pull_request.merged }}
          echo ${{ github.event.pull_request.head.label }} == 'changeset-release/main'

      - name: Check for changes in inlang/source-code/editor/package.json
        id: check_changes
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}
          API_URL="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/files"
          AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"

          # Fetch the list of files changed in the pull request
          RESPONSE=$(curl -s -H "$AUTH_HEADER" "$API_URL")

          # Check if the specific file is in the list of changed files
          echo "CHANGES=$(echo $RESPONSE | jq -r '.[] | select(.filename == "inlang/source-code/editor/package.json")')"
          if [ -z "$CHANGES" ]; then
            echo "No changes in inlang/source-code/editor/package.json"
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Changes in inlang/source-code/editor/package.json"
            echo "changes=true" >> $GITHUB_ENV

      - name: Trigger redeploy
        if: env.changes == 'true'
        run: |
          echo "Triggering redeploy via deploy hook"
          curl -X POST ${{ secrets.FINK_DEPLOY_HOOK_URL }}
